sudo: required
services:
  - docker

before_install:
  - docker build -t jrizzle1790/docker-react-kube -f Dockerfile.dev .

script:
  - docker run -e CI=true jrizzle1790/docker-react-kube npm run test -- --coverage