sudo: required
services:
  - docker

before_install:
  - docker build -t jrizzle1790/docker-react-kube -f Dockerfile.dev .

script:
  - docker run -e CI=true jrizzle1790/docker-react-kube npm run test -- --coverage

deploy:
  provider: elastikbeanstalk
  region: "us-east-1"
  app: "docker-react-kube"
  env: "DockerReactKube-env"
  bucket-name: "elasticbeanstalk-us-east-1-774887564425"
  bucket-path: "docker-react-kube"
  access_key_id: "AKIAJKPRNILA3VSZTSEQ"
  secret_access_key: "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"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
